### ISSUE TITLE
`generate_ghpages -h` throws

### ISSUE THREAD

**Issue by zoechi** [a14n/dart-ghpages-generator#8]
```
 (master) $ generate_ghpages -h
Unhandled exception:
FormatException: Could not find an option or flag "-h".
#0      Parser.validate (package:args/src/parser.dart:252)
#1      Parser.parseSoloOption (package:args/src/parser.dart:126)
#2      Parser.parse (package:args/src/parser.dart:76)
#3      ArgParser.parse (package:args/src/arg_parser.dart:121)
#4      main (http://localhost:39449/generate.dart:27)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by a14n** [comment]
Thanks for the report.
